### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MetalChain** [MC-U-Team/Usefull-Backpacks-1.10.x#10]
Dittos when with other mods or standalone

[crash-2019-06-22_16.54.03-client.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/3317275/crash-2019-06-22_16.54.03-client.txt)

**Comment by HyCraftHD** [comment]
This is likely due to wrong versions.
Which Backpack version do you use? UTeamCore version? Forge Version?
Try to update everything to the newest.

**Comment by MetalChain** [comment]
I was on 1.14.2 using the 1.14.2-1.7.0.27-SNAPSHOT Forge version, launched with the Forge ModLoader. I realize now I also didn't have the dependency, I'll try again with the dependency on .28 and see if that works, and update here.

**Comment by MetalChain** [comment]
[crash-2019-06-22_20.04.12-client.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/3317355/crash-2019-06-22_20.04.12-client.txt)

Using only u_team_core-1.14.2-2.5.3.114 and useful_backpacks-1.14.2-1.7.0.28

**Comment by HyCraftHD** [comment]
Your forge version is too old.
Please use at least 1.14.2-26.0.43

**Comment by MetalChain** [comment]
Yeah, no crash on .50, thanks. Not sure how I would have gotten such an old version having downloaded like last night, but I wouldn't have considered checking that. Thanks!

**Comment by HyCraftHD** [comment]
No problem :=)
Currently forge is changing and updating very fast so it is nessessary to update very often.
