### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Kirin92** [MC-U-Team/Usefull-Backpacks-1.10.x#12]
Hey~

I really want to use your mod but if I add the mod into the mods folder of my server it don't want to start. I also put in the other library mod that was required.

I use a Minecraft SpongeForge Server 1.12.2

**Comment by HyCraftHD** [comment]
Log? Also sponge forge is not officially supported. It might work or it might not.

**Comment by Kirin92** [comment]
I would send a log but it created a 0kb log with a weird date and time...
https://i.imgur.com/VPCZnmD.png

**Comment by HyCraftHD** [comment]
Okay thats not helpful :/ Can you try to setup a local server on your pc and try it there?

**Comment by Kirin92** [comment]
Nevermind. I took another backpack mod but I think it's because the core. I searched through the web and sponge loads after the core and causes the issue. I found a spongebootstrap and now it works with sponge.
https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275

**Comment by HyCraftHD** [comment]
The uteamcore is actually not a core mod just a normal library mod that adds some classes.
Since thats no matter anymore i'll close it. Reopen if needed.
