### ISSUE TITLE
Failure to Initialize Game and Crash

### ISSUE THREAD

**Issue by LionOfVerdun** [MC-U-Team/Usefull-Backpacks-1.10.x#14]
Alright, so I found a weird kinda glitch with either Useful Backpacks or U Team Core. Basically whenever I try and start my game running with forge and with both your mod and UTC the game will crash on initialization, and when I try to run it with just your mod Forge will stop me saying I need UTC, and if I try to run MC without UTC or your mod it crashes on Initialization and same if I run it with just UTC. This has only started with the latest update to 1.14.14. and I have updated both UTC and Useful backpacks to their respective 1.14.14 versions
[crash-2019-07-24_17.44.09-client.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/3428998/crash-2019-07-24_17.44.09-client.txt)

**Comment by HyCraftHD** [comment]
Hm tested it with theese versions and not crash. Does all versions match?
Do you have other mods installed?

**Comment by HyCraftHD** [comment]
![grafik](https://user-images.githubusercontent.com/7681220/61834512-8c05a700-ae78-11e9-801a-e0695dfe49a2.png)

**Comment by LionOfVerdun** [comment]
hey I checked and my forge version was 28.0.13 but even after I updated it to 28.0.14 the same crash happened
[crash-2019-07-24_18.28.21-client.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/3429072/crash-2019-07-24_18.28.21-client.txt)

**Comment by HyCraftHD** [comment]
Can you post the debug log?
The problem is this log does not contain any useful information to investigate the crash :/
Does it work when you remove useful backpacks? When you remove useful backpacks and uteamcore?

**Comment by LionOfVerdun** [comment]
I don't know where to find the Debug log, and It only works when I only have useful backpacks and even then it'll only take me as far as the loading screen where it tells me I need to install U Team Core. If I have bothe U Team core and Useful Backpacks installed it will crash and if I have Neither installed it'll crash
![Screenshot (11)](https://user-images.githubusercontent.com/53280192/61835658-58a82580-ae42-11e9-88bb-f51f26695b8e.png)
(Thats how far I get if I just have Useful BackPacks installed)

**Comment by HyCraftHD** [comment]
So it crashes when you have no usefulbackpacks and no uteamcore installed? Then there is an other issues which your installation.
Maybe try to delete the .minecraft folder and reinstall everything

**Comment by HyCraftHD** [comment]
Closed because not further response. If anything is still now working just hit me up or reopen.
