### ISSUE TITLE
[1.12.2] Backpack Dupe Bug

### ISSUE THREAD

**Issue by focamacho** [MC-U-Team/Usefull-Backpacks-1.10.x#15]
Steps to reproduce:
1. Open the backpack
2. Hold Shift & press the left mouse button to take the item and esc to close the backpack at the same time.
4. It's all

Video: https://youtu.be/BvOvosIYRQQ

**Comment by MrTroble** [comment]
Hallo,

and thanks for reporting this.
I guessed that this was in, we will take a look asap ...

Cheers
~MrTroble

**Comment by HyCraftHD** [comment]
Thanks for reporting!
I could recrate the dupe bug with this little macro script:
```java	
Robot bot = new Robot();
bot.keyPress(KeyEvent.VK_SHIFT);
bot.mousePress(InputEvent.BUTTON1_DOWN_MASK);
bot.keyPress(KeyEvent.VK_ESCAPE);
		
bot.keyRelease(KeyEvent.VK_SHIFT);
bot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK);
bot.keyRelease(KeyEvent.VK_ESCAPE);
```

This happend only on 1.12.2 (tested 1.14.4)

**Comment by HyCraftHD** [comment]
Fixed the dupe bug, at least I cannot reproduce it anymore 💃 
Also added backpacks in offhand are now useable
