### ISSUE TITLE
[1.14.4] Compatibility issue with OpenBackup

### ISSUE THREAD

**Issue by MattTheHuman** [MC-U-Team/Usefull-Backpacks-1.10.x#16]
Specifically with these versions:
Minecraft 1.14.4
Forge: 28.0.45
Useful Backpacks: 1.7.0.34
OpenBackup: 0.0.1.2

Mod says it loads find, but the items don't. Can't find them in JEI and they are also missing when upgrading worlds.

**Comment by HyCraftHD** [comment]
I could not reproduce. Its working fine for me: 
![grafik](https://user-images.githubusercontent.com/7681220/63091866-1749f800-bf60-11e9-811e-ede53075ef61.png)

Maybe update OpenBackup to the latest version?

**Comment by MattTheHuman** [comment]
Updated my OpenBackup to 0.0.1.3 and its all working.

**Comment by HyCraftHD** [comment]
Perfect! I'll close for now. Please let me know if any other incompatibilities occur.
