### ISSUE TITLE
Backpack disappears using scroll wheel

### ISSUE THREAD

**Issue by YagoDarkMoon** [MC-U-Team/Usefull-Backpacks-1.10.x#166]
In version 1.12.1.90 

I opened the backpack and accidentally used the scroll wheel while on the backpack icon in the inventory bar. It disappeared. The pack must be open for this to happen.

**Comment by HyCraftHD** [comment]
What other mods do you have installed? Also please use the issue template! I need some more information.

**Comment by HyCraftHD** [comment]
Closing because no response
