### ISSUE TITLE
[1.14.4] Weird crash with JEI

### ISSUE THREAD

**Issue by clonetrooper277** [MC-U-Team/Usefull-Backpacks-1.10.x#17]
Crash log:
https://pastebin.com/41wK8wHj
produced by just opening my inventory.
I just recently updated to Forge 28.0.49 on 1.14.4 if that's any help.

**Comment by HyCraftHD** [comment]
Thanks for the report. I'll have a lookt at it soon!

**Comment by clonetrooper277** [comment]
That was fast!

**Comment by clonetrooper277** [comment]
Should I report it  to the JEI developer?

**Comment by HyCraftHD** [comment]
Yep. Seems like an issue with jei.

**Comment by clonetrooper277** [comment]
Alright. Reporting it now!

**Comment by HyCraftHD** [comment]
One question. How can you reproduce it? Or did it just crash randomly?

**Comment by HyCraftHD** [comment]
Seems like this method was made private and jei tries to call it:
Class: net.minecraft.client.renderer.ItemRenderer
``` java
   private void renderModel(IBakedModel model, ItemStack stack) {
      this.renderModel(model, -1, stack);
   }
```

**Comment by clonetrooper277** [comment]
I can reproduce by just opening my inventory. The two mods were working perfectly before I updated Forge. Maybe that's the issue?

**Comment by HyCraftHD** [comment]
Well thats weird. Because I have no issues doing all this stuff with these versions.

**Comment by HyCraftHD** [comment]
Seems still be an issue on jei's side so I cannot do much about it :/
https://github.com/mezz/JustEnoughItems/issues/1680

**Comment by clonetrooper277** [comment]
Well, I'll just wait for mezz to fix it then.

**Comment by HyCraftHD** [comment]
Fixed in jei, so I close this issue here
