### ISSUE TITLE
[1.18.2] Fatal Crash on Backpack Open 

### ISSUE THREAD

**Issue by HalcyonSeas73** [MC-U-Team/Usefull-Backpacks-1.10.x#176]
### Bug description and reproduction steps

1. Add a Large Backpack to a creative inventory.
2. Open backpack with right click.
3. Game crashes.

Note, no option to select 1.18.2 from the dropdown list on Minecraft Version.

### Log files and Screenshots

https://paste.ee/p/CHnIh

### Used minecraft version

1.18.x

### Used forge version

40.0.12

### Used mod version

1.12.1.93

**Comment by HyCraftHD** [comment]
That is an issue with jei currently. Please report to jei
