### ISSUE TITLE
Request : add keybind

### ISSUE THREAD

**Issue by veniseberte** [MC-U-Team/Usefull-Backpacks-1.10.x#18]
Hi ! Thanks for making this mod, especially since there are currently no 1.14.4 backpack mods available.

I have a request, could you please add a keybind to open the backpack ? I added the Curios API mod and created a slot for the backpack, just to realize there is apparently no keybind to open it and you have to actually have the backpack in your hotbar so that you can right-click it and access its inventory. Unless I missed something.

Thanks !

**Comment by HyCraftHD** [comment]
Thanks alot!
A keybind globally cannot be added, because you can have more than one Backpack in your inventory so I don't know which one I should open.
What is excactly the Curios API? I had a request before where the requester didn't respond when I asked the question.
Does this mod just add slots where you can put items with functions and then assign a key to it?

**Comment by MrTroble** [comment]
It could be possible though to make a key bind that cycles threw the backpacks in your inventory.

So first press opens the first ... on second press it opens the second and so forth.

Cheers
~MrTroble

**Comment by veniseberte** [comment]
Other backpack mods I've used in the past would keybind the backpack only if it was equipped (since only one can be equipped at a time), so that when you pressed the key (usually "B" by default) it would open the inventory of the equipped backpack. If no backpack was equipped, pressing the key would do nothing.

By "equipped" I mean that these mods would either make it possible to put a backpack in place of the chestplate slot, or in a separate dedicated backpack slot. Most of these mods also added support for Baubles so that you could place the backpack in a Baubles slot instead.

As for the Curios mod, it is similar to Baubles if you know what that is. It seems Curios is a newer mod, and more flexible, as it allows both regular users and mod makers to add custom slots to the player's inventory so that they can equip items. I don't believe users can assign keybinds, though - those have to already be in place by the mod of the item in question. I recommend you check out the Curios API page on CurseForge (link [here](https://www.curseforge.com/minecraft/mc-mods/curios)), the developer has links to guides for users and for developers on how to add slots.

Thanks !

**Comment by HyCraftHD** [comment]
Curios is now integrated in the latest 1.16.1 build and might be also added for 1.15.2.
See here: https://www.curseforge.com/minecraft/mc-mods/useful-backpacks/files/3030447
