### ISSUE TITLE
doesnt work on the latest forge version

### ISSUE THREAD

**Issue by KapGlonk** [MC-U-Team/Usefull-Backpacks-1.10.x#19]
please help me

**Comment by HyCraftHD** [comment]
Hello.
Can you please specify the versions and send the log?

**Comment by Morpheus1101** [comment]
1.14.4 with forge 28.0.9 using mod version 1.7.0.34 it errors loading client saying it needs Forge 28.0.13 or higher.

**Comment by HyCraftHD** [comment]
Please use a newer forge version then. Because 1.14.4 is still a very beta build you should always update to the latest forge version which is currently 28.0.83

**Comment by Morpheus1101** [comment]
Arg, apologies, stupid Curse client...i though 28.0.9 was 28.0.90 .. i will remedy this which will solve all my issues

**Comment by HyCraftHD** [comment]
As there is no response from the opener I'll close this for now. Please let me know if any other bugs occur.
