### ISSUE TITLE
[1.19.2] Add compatibility with Fabric

### ISSUE THREAD

**Issue by AdisonCavani** [MC-U-Team/Usefull-Backpacks-1.10.x#194]
### Detailed description of the feature

Since `uteamcore` is compatible with Fabric API, I was wondering if you could make this mod also compatible with Fabric.

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
Done in 1.20
