### ISSUE TITLE
[1.19.2] Use partially filled backpacks for upgraded crafting

### ISSUE THREAD

**Issue by L9Tigrotto** [MC-U-Team/Usefull-Backpacks-1.10.x#201]
### Detailed description of the feature

It would be nice if to craft the medium-sized backpacks it were possible to use all the small backpacks with color determined by the small backpack used in the center of the crafting. Obviously the medium backpack should contain all the objects that were contained in the small backpack. This way of crafting backpacks could also apply to large backpacks.

Something like that
![SmallBackpackInventory](https://user-images.githubusercontent.com/43849125/227695919-208521ed-2417-4d2e-ba3d-9bff8af83225.png)
![MediumBackpackRecipe](https://user-images.githubusercontent.com/43849125/227695922-992c23c5-c365-4270-9534-8cc216878d77.png)

### Verify feature request

- [x] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
This is already possible if you use white wool for all wool slots. Then the color of the small / medium backpack is used.

**Comment by L9Tigrotto** [comment]
Oh true, it's jei that did not show it to me. Mb!
