### ISSUE TITLE
Crash on Game Launch(1.14.4)

### ISSUE THREAD

**Issue by hsrco** [MC-U-Team/Usefull-Backpacks-1.10.x#21]
Hey folks, I'm sorry if this seems noob-ish, and sorry if I'm posting this in the wrong place, but I'm trying to install this mod onto my 1.14.4 version. Other than this mod, Fabric, and a mod called Mouse Wheely (similar to InvTweaks), my game is vanilla MC 1.14.4 and is launched and configured through MultiMC. The game fails to run, throws me back to MMC, and spits out a crash report, which I will attatch for your viewing. I was wondering if someone could tell me what is going on? Thanks in advance.
I am available to give further information about my install.

[crash-2019-10-05_20.36.31-client.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/3693642/crash-2019-10-05_20.36.31-client.txt)

**Comment by hsrco** [comment]
Also, sorry that I haven't tagged this, I'm still struggling my way through learning how Github works.

**Comment by hsrco** [comment]
I posted this in the wrong goddamn github... please ignor my dumbness!

**Comment by MrTroble** [comment]
If you still don't know what to do: this seems to be an issue with Fabric. So please consider writing an issue there. :)
I hope I could help tho

Cheers
~MrTroble

**Comment by HyCraftHD** [comment]
Just to let you know @hsrco. Forge is not compatible with fabric. Therefore no forge mod including all my mods aren't compatible with fabric.
