### ISSUE TITLE
[1.20] No Key Bindings for Backpacks

### ISSUE THREAD

**Issue by HalcyonSeas73** [MC-U-Team/Usefull-Backpacks-1.10.x#223]
### Bug description and reproduction steps

1. Open the Minecraft Menu>Options>Key Binds
2. Search for Useful Backpacks' Open Backpack keybind via scrolling

### Log files and Screenshots

![image](https://github.com/MC-U-Team/Useful-Backpacks/assets/84727791/0b562088-8917-4402-93cf-96762c44999a)

### Used minecraft version

1.20.x

### Used forge or fabric version

46.0.14

### Used mod version

2.0.0.113

**Comment by HyCraftHD** [comment]
Will be implemented when curios updates to 1.20.
(Oh, they have released yesterday. I'm working on it)

**Comment by HyCraftHD** [comment]
Implemented for 1.20 and 1.20.1 releases for fabric and forge (with curios or trinkets integration)
