### ISSUE TITLE
[1.20.1] Changing color with dye or wool isn't working on Server

### ISSUE THREAD

**Issue by SeagullMoe** [MC-U-Team/Usefull-Backpacks-1.10.x#235]
### Bug description and reproduction steps

Basically what the title says, I'm trying to changing the color of the backpack with dyes and I even tried making one with purple wool but still getting the default backpack

It works perfectly on Singleplayer but not in my Aternos server, don't know if that has anything to do with it but the server is running the same version of both the main mod and UTeamCore that I'm running on my client. The different colored backpacks do appear in creative mode but whenever I try putting them in my inventory they just turn into a default backpack again, so yeah. The only thing that may be making it not work is the fact that I'm using Mohist instead of Forge or Fabric as a mod loader, since that allows me to use both mods and plugins in my server with no major complications.

Hope I can get some help on this!

Minecraft version: 1.20.1
Mohist version: 49
Mod version: 2.0.1.119
UTeamCore: 5.1.2.266

### Log files and Screenshots

Not necessary I believe

### Used minecraft version

1.20.x

### Used forge or fabric version

47.0.3

### Used mod version

2.0.1.117

**Comment by SeagullMoe** [comment]
UPDATE: Mohist does run Forge, and the version is 47.0.3, sorry, didn't notice at first

**Comment by HyCraftHD** [comment]
Cannot reproduce with a forge server. Might be an issue with Mohist (unsupported) or an other mod.
Please report if you can reproduce this with a clean forge or fabric server

**Comment by HyCraftHD** [comment]
Closing as there is no response
