### ISSUE TITLE
[1.20.1] Filters are not craftable in Fabric version

### ISSUE THREAD

**Issue by gamerpotion** [MC-U-Team/Usefull-Backpacks-1.10.x#241]
### Bug description and reproduction steps

The filters dont seem to be craftable in Fabric version of the mod.
looking at the recipe, seems its a tag issue?

```{"type":"minecraft:crafting_shaped","category":"misc","key":{"D":{"tag":"forge:gems/diamond"},"E":{"tag":"forge:end_stones"},"I":{"tag":"forge:ingots/iron"},"L":{"item":"minecraft:leather"},"R":{"tag":"forge:dusts/redstone"},"S":{"item":"minecraft:string"},"W":{"tag":"minecraft:wool"}},"pattern":["WLW","RDS","IEI"],"result":{"item":"usefulbackpacks:filter_item"},"show_notification":true}```

### Log files and Screenshots

<img src="https://media.discordapp.net/attachments/1126427014866415696/1126427015118061599/2023-07-06_01_17_52-Window.png" />

<img src="https://media.discordapp.net/attachments/1126427014866415696/1126427015436836905/2023-07-06_01_17_58-Window.png" />

### Used minecraft version

1.20.x

### Used forge or fabric version

0.14.21

### Used mod version

useful_backpacks-fabric-1.20.1-2.0.1.120.jar

**Comment by HyCraftHD** [comment]
Fixed in this version: 
![image](https://github.com/MC-U-Team/Useful-Backpacks/assets/7681220/4e5cdb66-74bc-4281-8676-c1bb26cf1191)
