### ISSUE TITLE
[1.14.4] Cannot make colored backpacks with different wools.

### ISSUE THREAD

**Issue by fuzzyweapon** [MC-U-Team/Usefull-Backpacks-1.10.x#25]
**Describe the bug**
If I make a backpack in survival mode, it doesn't matter what color wool I use, I will always get brown leather (default).  This is also the only color that shows up in JEI. Dying the backpack afterwards still works.

**To Reproduce**
Steps:
1.  Login to an MP or load up SP.
2.  Get the materials to make a white backpack (4 white wool blocks, string, and four leather).
3.  Load the materials into a vanilla crafting table in the pattern for a small backpack.
4.  Observe output backpack.
5.  Take resulting backpack out.
6.  Observe resulting backpack color is default leather.

**Expected behavior**
In past versions, you could bypass having to use dye by just making the backpack out of a certain color of wool.  This seems to have broken or has the design just been changed?

**Screenshots**
Not really necessary.

**Versions**
- Mod version: 1.7.1.38
- Minecraft version: 1.14.4
- Forge version: 28.1.26
- UTeamCore version: 2.7.3.132

**Log (if crash occurs)**
No crash log and nothing useful during bootup or running to indicate why this is happening (in latest.log or debug.log).

**Comment by fuzzyweapon** [comment]
Just tested this in .36 SP and it happens there too.

**Comment by fuzzyweapon** [comment]
Looks like this was caused by an update of Forge from 28.1.10 to 28.1.26.

I just tested in .34 which I know it was working with 28.1.10 before, and it's occurring there too when using 28.1.26. :/

**Comment by HyCraftHD** [comment]
Hello,
This behaviour is kind of on purpose. 4 white wool blocks in the crafting recipe symbolize a "neutral" color and don't change the color at all. I'm not 100% happy with this solution but haven't found any better yet. I'm open for any suggestions.
To create a full white backpack use 3 white wool and a yellow and then color it with white dye again.
~ Johannes

**Comment by fuzzyweapon** [comment]
Ahhh, cool.  Good to know.  Closing this.  I went ahead and confirmed that colored backpacks are still working for other colors (given my own bug summary and bad short term memory :D).  Testing with orange wool, everything looks fine.
