### ISSUE TITLE
[1.20.2] Allow players open backpack that use Fabric, on Forge servers

### ISSUE THREAD

**Issue by MgmTak1Poveril** [MC-U-Team/Usefull-Backpacks-1.10.x#260]
### Detailed description of the feature

Apparently you can't open them this way, please add this.

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by HyCraftHD** [comment]
Not possible due to differences in modloader networking.
You should use the same modloader on the client and the server.
