### ISSUE TITLE
[1.12.2] Useful Backpacks Dupe Bug

### ISSUE THREAD

**Issue by focamacho** [MC-U-Team/Usefull-Backpacks-1.10.x#30]
**Describe the bug**
Dupe items using backpacks

**To Reproduce**
1. Open and drop a backpack at the same time
2. Take the itens from the backpack gui, and the backpack on the ground
3. It's all

**Expected behavior**
Be impossible to pick up the items in the backpack

**Versions**
- Mod version: 1.5.1.42
- Minecraft version: 1.12.2
- Forge version: Latest 1.12.2
- UTeamCore version: 2.2.4.133

Obs: It don't happens using UsefulBackpacks 1.5.1.35 & U-Team-Core 2.4.107

**Comment by HyCraftHD** [comment]
Thanks for the report. The issue appeared some time ago (#15 ) too and was fixed there. I'll try to reproduce it and then try to fix it.

**Comment by xxlio109** [comment]
When throwing the backpack, open the backpack GUI, then throw the items inside, close the GUI, pick up all the items, and copy an extra item 

Versions

Mod version: 1.9.0.52
Minecraft version: 1.15.2
Forge version: Latest 1.15.2
UTeamCore version: 2.10.0.146

**Comment by HyCraftHD** [comment]
Tried to reproduce it but failed. Do you use it on a server or an a single player world?
What do you press first to trigger that bug. Q or Rightclick?

**Comment by focamacho** [comment]
It's very hard to reproduce without some lag, so to do it in singleplayer you'll need a macro.
Press Rightclick first.

**Comment by HyCraftHD** [comment]
Tried it with a macro which like 1ms delay but could not get it to work :/
I'll try it in singleplayer with a high ping simulator.

Are the items real items or ghost items?

**Comment by xxlio109** [comment]
server  .  real items

**Comment by HyCraftHD** [comment]
Thanks. Got the bug going on a local server with a network test tool so simulate a 4000ms rtt: 
![grafik](https://user-images.githubusercontent.com/7681220/73865540-b67ee680-4843-11ea-8cd0-e77b6cfa3f7e.png)

To get the bug:
 - Open the backpack
 - Before the gui opens press q
 - When the gui opens the backpack gets drops afterwards but the gui is still open an you can remove items from that.

*Looking forward to fix that*

**Comment by HyCraftHD** [comment]
Found a fix. Will release updates for 1.12.2, 1.14.4 and 1.15.2!
Thanks for reporting this bug!

```java
@Override
public boolean onDroppedByPlayer(ItemStack item, EntityPlayer player) {
	return !(player.openContainer instanceof ContainerBackPack);
}
```
