### ISSUE TITLE
[1.15.2] Curseforge tag ambiguity.

### ISSUE THREAD

**Issue by plaguewolf** [MC-U-Team/Usefull-Backpacks-1.10.x#33]
Describe the bug
Doesnt work on fabric.

To Reproduce

Install on fabric instead of forge.
Load minecraft
???
Profit
Expected behavior
On the curseforge page, there are options available to tag wether a mod is Forge or Fabric. Please use them. otherwise its just chaos and confusion.

Screenshots

Versions

Minecraft version: 1.15.2 [Applicable to whatever version
Forge version: Latest as of report
UTeamCore version: Latest as of report
Log (if crash occures)
Link to crash log

**Comment by MrTroble** [comment]
See other issue

**Comment by MrTroble** [comment]
https://github.com/MC-U-Team/U-Team-Core/issues/31#issuecomment-579915439
