### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by Cilas0080** [MC-U-Team/Usefull-Backpacks-1.10.x#36]
**Describe the bug**
i cant use the backpacks at all

**To Reproduce**
2. Do this '....'

**Expected behavior**
i cant create /craft backpacks and the dont work if i take them from creative mode
**Screenshots**

**Versions**
- Mod version: 1.15.2
- Minecraft version: 1.15.2
- Forge version: 1.15.2
- UTeamCore version: 1.15.2

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
Well, first of. Do you play on a server? If so, is the mod installed on the server?
Also, the versions are not the right ones. We need the mod versions not the minecraft version 4 times.

**Comment by MrTroble** [comment]
From what I know the issue persists on the server side only

**Comment by MrTroble** [comment]
Is there a crash happening? If so could you include a log?

**Comment by KingSassa** [comment]
I have the same issue. Not playing on a server. the backpack mod worked beautifully in the  previous version, but in 1.9.4.63 it fails. when the backpack is in the hotbar and the slot is selected, right clicking the mouse does not open the backpack. instead it tries to place the backpack.

**Comment by HyCraftHD** [comment]
Do you have optifine installed?

**Comment by HyCraftHD** [comment]
As there is no response from any of the reporters, I'll close this issue. If the issue still persists please open a new issue.
