### ISSUE TITLE
Backpack Eats ALL the items when upgrading.

### ISSUE THREAD

**Issue by SirTwsted** [MC-U-Team/Usefull-Backpacks-1.10.x#4]
Major Major Major problem with your mod....!!
If you have any items in your medium backpack and you upgrade to a large backpack without taking out the items from the medium backpack (because you might have forgotten to take them out)
You lose ALL  ALL ALL the contents in the backpack.
.
I lost a bunch of diamonds, Tinker well advanced tools, Ender pearls, and other machine tools.
Please fix this problem.
Wooow, cant believe the mod ate all my items just because I upgraded the back and left the items inside the backpack.
Very frustrating.

**Comment by HyCraftHD** [comment]
Well this issues is known and is fixed in 1.13.2. 
I'll have a look to fix it in 1.12.2.

**Comment by SirTwsted** [comment]
Thank you Thank you Thank you  :D

**Comment by HyCraftHD** [comment]
I decided, that i wont backport this features. I think its not that nessessary, because no other backpackmod supports this.

**Comment by HyCraftHD** [comment]
Well, i just added this features ... It was quite easy lol.
