### ISSUE TITLE
[1.16.1] Dupe

### ISSUE THREAD

**Issue by WhitePhant0m** [MC-U-Team/Usefull-Backpacks-1.10.x#41]
**Describe the bug**
You can dupe with backpacks

**To Reproduce**
Steps to reproduce the behavior:[![Image from Gyazo](https://i.gyazo.com/20630bf2f3661f4a7350fe332320204c.gif)](https://gyazo.com/20630bf2f3661f4a7350fe332320204c)

**Expected behavior**
No duping

**Screenshots**
See gif above

**Versions**
- Mod version: Useful-Backpacks-1.16.1-1.11.2.74
- Minecraft version: 1.16.1
- Forge version: 32.0.108
- UTeamCore version: U-Team-Core-1.16.1-3.1.3.

You could store the items in an inventory with an UUID and have the bags access that inventory instead of storing the items on the bag itself, that should make it impossible to dupe the contents of a bag even if players manage to dupe the bags somehow but i don't know if this would fix the dupe itself

**Comment by HyCraftHD** [comment]
~~Well thats a bug by the item router mod or curios, but not a dupe bug by useful backpacks.~~

I know that it is possible to store the content with a uuid in a seperate place, but that has some downsides, like when to delete the stuff, etc. I don't really wanna deal with that so I'll leave it as it is now and fix dupe bugs directly related to useful backpacks.

**Comment by HyCraftHD** [comment]
Hey, I think I found a fix for that. I tried it and cannot reproduce with this fix. Can you please confirm that by updating to one of these versions?
![image](https://user-images.githubusercontent.com/7681220/91980469-98b92780-ed27-11ea-9864-dbc9f6e99bec.png)

Thanks!
