### ISSUE TITLE
Crash during modpack startup ( custom Crackpack 3) 

### ISSUE THREAD

**Issue by x7HsN** [MC-U-Team/Usefull-Backpacks-1.10.x#43]
i modified crackpack 3 modpack with extra mods ,,, but when i started the modpack it gave me this crash ,,,
and while reading it ( i think the problem is with the mod useful backpacks )

[crash-2020-08-31_00.28.37-client.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/5147512/crash-2020-08-31_00.28.37-client.txt)

**Comment by HyCraftHD** [comment]
Do **not** download the -dev versions.
You downloaded the -dev uteamcore version which is only for the development environment

**Comment by x7HsN** [comment]
Thanks for the reply …. Appreciated


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
