### ISSUE TITLE
Ability to disable backpack sizes, or rebalance recipe.

### ISSUE THREAD

**Issue by EQGShadow** [MC-U-Team/Usefull-Backpacks-1.10.x#44]
Hello!

Love this mod, especially because of the curio support. But I find that the large backpack is much too powerful for its recipe, and small is too small. I was wondering if there was a way to disable certain sizes, or adjust the size of the backpacks, or a way to adjust the recipe to reflect how useful it is.

Thankyou!

**Comment by HyCraftHD** [comment]
Hello,
Thank you!
Sure, there are datapacks which allow you to override the recipes. If you want to completly remove them crafttweaker is the easier way to go.
