### ISSUE TITLE
[1.12.2] Dupe Bug

### ISSUE THREAD

**Issue by focamacho** [MC-U-Team/Usefull-Backpacks-1.10.x#46]
**Describe the bug**
Dupe items using backpacks. It seems to happen only when Sponge is installed.

**To Reproduce**
1. Open and drop a backpack at the same time
2. Take the itens from the backpack gui, and the backpack on the ground
3. That's all

**Expected behavior**
Be impossible to pick up the items in the backpack

**Versions**
- Mod version: 1.5.3.59
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2854
- UTeamCore version: 2.2.5.147

I did a quick fix but I don't know if it's the best way to fix it.
https://github.com/Focamacho/Useful-Backpacks/commit/98edcc80dda9d7a8b8e672edfdb099bec039a0b4

**Comment by HyCraftHD** [comment]
Hello, thanks for the report. These issues are fixed on 1.15.2+ but 1.12.2 is kinda unsupported.
I'm happy if you want to pr the fixes:

Your fix seems to adress the main cause though so I'm happy if you want to PR that. (Would be nice if you may have a look at the oder dupe fixes and if its possible to backport them.)

https://github.com/MC-U-Team/Useful-Backpacks/blob/436f404d77dfda3b1d59d17abe2ec4c5302c5f6a/src/main/java/info/u_team/useful_backpacks/container/BackpackContainer.java#L92-L100

https://github.com/MC-U-Team/Useful-Backpacks/blob/436f404d77dfda3b1d59d17abe2ec4c5302c5f6a/src/main/java/info/u_team/useful_backpacks/container/BackpackContainer.java#L103-L110

https://github.com/MC-U-Team/Useful-Backpacks/blob/436f404d77dfda3b1d59d17abe2ec4c5302c5f6a/src/main/java/info/u_team/useful_backpacks/item/BackpackItem.java#L101-L104

**Comment by focamacho** [comment]
Of course!

**Comment by HyCraftHD** [comment]
Release is here: https://www.curseforge.com/minecraft/mc-mods/useful-backpacks/files/3104696
