### ISSUE TITLE
Mod doesn't load in 1.13.2 (latest version)

### ISSUE THREAD

**Issue by Gbergz** [MC-U-Team/Usefull-Backpacks-1.10.x#5]
Game doesn't boot with this mod installed.

Logs:
[Hastebin Link Paste](https://hastebin.com/nawirogibu)

Screenshot:
[Imgur Link](https://i.imgur.com/5Evbmyj.png)

**Comment by HyCraftHD** [comment]
UTeamCore seems missing. Also keep in mind this is a very unstable alpha release, and it will not work in servers i guess.

**Comment by Gbergz** [comment]
Yes sorry forgot to see if there was a core mod needed. Well it seems to be still not booting.

Screenshot:
[Imgur Link](https://i.imgur.com/xZ0yKZt.png)

Logs:
[Hastebin Link Paste](https://hastebin.com/kotujetare)

**Comment by HyCraftHD** [comment]
Thanks I'll have a look into it soon

**Comment by HyCraftHD** [comment]
Thats caused by a new forge build tonight. 22 will work, 26 wont. 
I'll fix it tody.
Thanks for reporting.

**Comment by HyCraftHD** [comment]
Apparently i cannot reproduce this. I'll gonna update straight to 27

**Comment by HyCraftHD** [comment]
The issues was the cursegradle plugin which did not correctly depend on the build tasks thus uploading the dev jar. This is the non obfuscated jar and will only work in build environment.

I fixed the issues and the latest uteamcore and usefulbackpacks file is correct and will work at least for forge build 27
