### ISSUE TITLE
Game Crashes During World Load

### ISSUE THREAD

**Issue by TheBeefBai** [MC-U-Team/Usefull-Backpacks-1.10.x#51]
Hi there. Whenever I load a world that I have previously used this mod in, namely my main survival world, the mod causes the game to crash just after it reads the world data. I've looked at the forge crash log and from what I can tell it says something about not being able to load a server config file, but I never deleted said file from my configs folder. I've tried moving the mod from the mods folder and moving it back in, deleting any configs used by the mod and even downloading a new .jar file (the new file being the same version as the older one) but with no success.
[latest.log](https://github.com/MC-U-Team/Useful-Backpacks/files/5742460/latest.log)
[crash-2020-12-25_22.21.53-server.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/5742461/crash-2020-12-25_22.21.53-server.txt)
Minecraft 1.16.4
Forge 35.1.13
Mod Version 1.16.4-11.1.6.86

**Comment by MrTroble** [comment]
Hello,

your config file seams to be corrupted ... could you try to delete the one you are using?

Cheers
~MrTroble

**Comment by TheBeefBai** [comment]
I tried deleting the config from the configs folder in .minecraft and that didn't fix it but when I went into my world folder I found the server config file in a subfolder and deleted that which worked. Thanks for your help 👍

**Comment by MrTroble** [comment]
Your welcome, glad it fixed it.

Cheers
~MrTroble
