### ISSUE TITLE
[1.16.4] Backpack disappears with keepInventory

### ISSUE THREAD

**Issue by alguienxd** [MC-U-Team/Usefull-Backpacks-1.10.x#52]
**Describe the bug**
When playing in a minecraft world with keepInventory on, when I die my entire inventory is retained, save for my backpacks and their contents which just vaporize from my world. There might be an interaction with corail tombstone but I'm not sure.

**To Reproduce**
1. Use keepInventory = true
2. Have a backpack with items in the player inventory
3. Die

**Expected behavior**
Once the player dies and the respawn button is clicked, the backpack will be forever lost nowhere to be found. This only seems to occur with the first backpack found. However, sucessive backpacks don't seem to cause this issue

**Screenshots**
![2021-01-24_12 38 06](https://user-images.githubusercontent.com/46161647/105629115-67a9d280-5e41-11eb-824d-8ed0f68088e3.png)
![2021-01-24_12 38 23](https://user-images.githubusercontent.com/46161647/105629116-68426900-5e41-11eb-96d7-6ae8a7244e73.png)
![2021-01-24_12 38 34](https://user-images.githubusercontent.com/46161647/105629119-6a0c2c80-5e41-11eb-9dd0-fdecc346ca32.png)
![2021-01-24_12 38 46](https://user-images.githubusercontent.com/46161647/105629120-6aa4c300-5e41-11eb-8525-5c6d4bc68a16.png)
![2021-01-24_12 39 01](https://user-images.githubusercontent.com/46161647/105629121-6b3d5980-5e41-11eb-9617-51e6781f36af.png)
![2021-01-24_12 39 04](https://user-images.githubusercontent.com/46161647/105629122-6b3d5980-5e41-11eb-8997-b0a8bc82843d.png)
![2021-01-24_12 39 08](https://user-images.githubusercontent.com/46161647/105629123-6bd5f000-5e41-11eb-8db7-383d1af3fd67.png)
![2021-01-24_12 39 21](https://user-images.githubusercontent.com/46161647/105629124-6bd5f000-5e41-11eb-85b9-078275f54ae2.png)
![2021-01-24_12 39 33](https://user-images.githubusercontent.com/46161647/105629125-6c6e8680-5e41-11eb-8c35-e892a0e59837.png)
![2021-01-24_12 39 41](https://user-images.githubusercontent.com/46161647/105629126-6d071d00-5e41-11eb-9b70-e07b5292ac38.png)
![2021-01-24_12 39 50](https://user-images.githubusercontent.com/46161647/105629127-6d071d00-5e41-11eb-98ce-8eeebe7047eb.png)
![2021-01-24_12 39 55](https://user-images.githubusercontent.com/46161647/105629128-6d9fb380-5e41-11eb-9cd8-df52eb621a8b.png)

**Versions**
- Mod version: 1.11.6.86
- Minecraft version: 1.16.4
- Forge version: 35.1.36
- UTeamCore version: 3.1.17.191

**Comment by TheFlash787** [comment]
Have you looked in your back bauble slot? We had this exact issue and found it inside of the bauble slot for back.

**Comment by Corail31** [comment]
Tombstone has a config for equipping slots on death respawn, so it can be related.

**Comment by HyCraftHD** [comment]
@alguienxd Do you have other mods installed? Have you checked what @TheFlash787 and @Corail31 suggested?

**Comment by HyCraftHD** [comment]
As there is not response I'll close. Please let me know if the issue still persists.
