### ISSUE TITLE
Full Russian translation

### ISSUE THREAD

**Issue by Rick-Zero** [MC-U-Team/Usefull-Backpacks-1.10.x#53]
[ru_ru.zip](https://github.com/MC-U-Team/Useful-Backpacks/files/5865293/ru_ru.zip)

**Comment by HyCraftHD** [comment]
Thank you very much!
If you want credits in github you can make a pull request to change the current ru_ru language file: https://github.com/MC-U-Team/Useful-Backpacks/blob/1.16.5/src/main/resources/assets/usefulbackpacks/lang/ru_ru.json

**Comment by HyCraftHD** [comment]
Will be published soon as a new 1.16.5 build.
Thanks!
