### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by firestorm2039** [MC-U-Team/Usefull-Backpacks-1.10.x#56]
i installed this to mods folder along with Uteamcore (both at 1.16.4) as thats the version of forge i have.

when the game starts to load i get game crashed message
any reason why?

**Comment by HyCraftHD** [comment]
Please provide a crashlog and use the bug template.

**Comment by firestorm2039** [comment]
> Please provide a crashlog and use the bug template.

Where would I get a copy of crash log? (I am new to mods on minecraft and not very computer knowledgeable lol).

Also I didn't see no bug template sorry

**Comment by MrTroble** [comment]
You can find it under `%appdata%\.minecraft\crash-reports\`

**Comment by firestorm2039** [comment]
> You can find it under `%appdata%\.minecraft\crash-reports\`

Thank you, I will see what's there, will do this later as I am pretty busy today

**Comment by firestorm2039** [comment]
> You can find it under `%appdata%\.minecraft\crash-reports\`

i have just looked in there and there isnt a crash report for the day it crashed, latest 1 says 30/01/2021 and i didnt have this mod then?

**Comment by HyCraftHD** [comment]
Then please install the mods and run the game again. Then please send us the crashlog and the debug.log file: %appdata%\.minecraft\logs\

Do you use the normal minecraft launcher or curseforge?

**Comment by firestorm2039** [comment]
> Then please install the mods and run the game again. Then please send us the crashlog and the debug.log file: %appdata%.minecraft\logs\
> 
> Do you use the normal minecraft launcher or curseforge?

i use curseforge 1.16.4 (i have otehr mods running on it, but i dont think they will conflict with each other?, i seem to get this error with quite a few popular mods i try and use.

[debug.log](https://github.com/MC-U-Team/Useful-Backpacks/files/5952767/debug.log)

[crash-2021-01-30_22.52.19-server.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/5952778/crash-2021-01-30_22.52.19-server.txt) this is the latest crash report is crash reports folder, but it isnt dated today, it seem any crashes i get when loading the game doesnt show here, only in game crashes

**Comment by HyCraftHD** [comment]
The error is from a mod called: mining-helmet. Try to remove that one and retry

**Comment by HyCraftHD** [comment]
And the crashreport only has these mods: 
```
		forge-1.16.4-35.0.15-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		Lucky-Block-Mod-1.16.4.jar                        |Lucky Block                   |lucky                         |1.16.4-1            |DONE      |NOSIGNATURE
		TreeChop-1.16.4-0.11.3.jar                        |treechop                      |treechop                      |0.11.3              |DONE      |NOSIGNATURE
		Corail-Tombstone-Mod-1.16.4.jar                   |Corail Tombstone              |tombstone                     |1.16-6.2.2          |DONE      |NOSIGNATURE
		forge-1.16.4-35.0.15-universal.jar                |Forge                         |forge                         |35.0.15             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		WAWLA-1.16.4-7.0.2.jar                            |WAWLA                         |wawla                         |7.0.2               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		Cyclic-Mod-1.16.4.jar                             |Cyclic                        |cyclic                        |1.16.3-0.9.2        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |DONE      |NOSIGNATURE
```

No mod is from u-team

**Comment by firestorm2039** [comment]
> Then please install the mods and run the game again. Then please send us the crashlog and the debug.log file: %appdata%.minecraft\logs\
> 
> Do you use the normal minecraft launcher or curseforge?

here is a picture of the error and the mods i have installed
![jhgvhjlkj](https://user-images.githubusercontent.com/75093996/107397072-3e9e6880-6af6-11eb-9d36-b8788f643424.png)


![Untitled](https://user-images.githubusercontent.com/75093996/107396834-0a2aac80-6af6-11eb-8f52-ab5272ad715b.png)

**Comment by HyCraftHD** [comment]
Remove mining-helmet and try again.

**Comment by firestorm2039** [comment]
> And the crashreport only has these mods:
> 
> ```
> 		forge-1.16.4-35.0.15-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
> 		Lucky-Block-Mod-1.16.4.jar                        |Lucky Block                   |lucky                         |1.16.4-1            |DONE      |NOSIGNATURE
> 		TreeChop-1.16.4-0.11.3.jar                        |treechop                      |treechop                      |0.11.3              |DONE      |NOSIGNATURE
> 		Corail-Tombstone-Mod-1.16.4.jar                   |Corail Tombstone              |tombstone                     |1.16-6.2.2          |DONE      |NOSIGNATURE
> 		forge-1.16.4-35.0.15-universal.jar                |Forge                         |forge                         |35.0.15             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
> 		WAWLA-1.16.4-7.0.2.jar                            |WAWLA                         |wawla                         |7.0.2               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
> 		Cyclic-Mod-1.16.4.jar                             |Cyclic                        |cyclic                        |1.16.3-0.9.2        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
> 		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |DONE      |NOSIGNATURE
> ```
> 
> No mod is from u-team

yeah i know, thats what i mean, it's not showing up in the crash report folder.
i have just removed mining helmet (only installed that 1 today though), still getting same crash report. here is a screen shot and debug file again
[debug.log](https://github.com/MC-U-Team/Useful-Backpacks/files/5952869/debug.log)
![Untitled](https://user-images.githubusercontent.com/75093996/107398275-5de9c580-6af7-11eb-9aa1-9eee8f5d756d.png)

**Comment by firestorm2039** [comment]
> Remove mining-helmet and try again.

i have just tried having u-team core mod and useful backpacks installed (removed all other mods from folder) and i still get error code :(

**Comment by HyCraftHD** [comment]
Well the crashlog still indicates some weird coremod mixin stuff. Can you send me the log from only uteamcore and usefulbackpacks please?

**Comment by firestorm2039** [comment]
> Well the crashlog still indicates some weird coremod mixin stuff. Can you send me the log from only uteamcore and usefulbackpacks please?

[debug.log](https://github.com/MC-U-Team/Useful-Backpacks/files/5952948/debug.log)
[latest.log](https://github.com/MC-U-Team/Useful-Backpacks/files/5952961/latest.log)

**Comment by HyCraftHD** [comment]
Seems like a broken forge installation.
Please try to update to forge 35.0.37 (latest forge version on the website)

If that does not work try to delete the .minecraft folder (remember to backup worlds / resourcepacks / etc)
and try to reinstall everthing

**Comment by firestorm2039** [comment]
> Seems like a broken forge installation.
> Please try to update to forge 35.0.37 (latest forge version on the website)
> 
> If that does not work try to delete the .minecraft folder (remember to backup worlds / resourcepacks / etc)
> and try to reinstall everthing

thank you
updating forge to 35.1.37 worked, i thought forge automatically updates lol, my mistake.

much apricated, hopefully now other mods i tried will now work. 

EDIT:
yes all other mods that i downloaded that was also causing game to crash are now working as well.

**Comment by HyCraftHD** [comment]
Nice Glad it works now!
