### ISSUE TITLE
1.16.4 Can no longer load specific world with this mod installed

### ISSUE THREAD

**Issue by JoelSzabo** [MC-U-Team/Usefull-Backpacks-1.10.x#57]
I have been using this mod for several months with no issues on 1.16.4. Yesterday (7/02/21) the game suddenly crashed and will no longer allow me to open the world I was playing at the time (others open fine) unless i remove this particular mod from my mod folder. Each time I try to enter the world with this mod, the game becomes unresponsive on the loading screen, and then crashes. I get the same crash log each time. When I remove this mod the world loads without issue.

I have updated forge to 1.16.5 in the process of trying to solve the issue, as well as allocated more RAM. I have also updated to newest versions of the UTeamCore mod as well as Useful Backpacks. None of these changes have made a difference.

Original Crash:
[crash-2021-02-07_22.37.56-server.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/5940492/crash-2021-02-07_22.37.56-server.txt)
Latest attempt at loading the world:
[crash-2021-02-08_12.51.56-server.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/5940493/crash-2021-02-08_12.51.56-server.txt)

**Versions**
- Mod version: 1.16.4-1.11.6.86   AND   1.16.4-1.11.6.87
- Minecraft version: 1.16.4   AND   1.16.5
- Forge version: 1.16.4-35.1.13   AND   1.16.5-36.0.15
- UTeamCore version: 1.16.4-3.1.16.190   AND   1.16.4-3.1.17.192

I hope you can help - I would also like to know if I will have lost the contents of the bags I had previously, since I have changed versions and also loaded the world without the mod.

**Comment by HyCraftHD** [comment]
This is caused by a corrupted config file inside your world. Please delete the file usefulbackpacks-server.toml file inside your world/serverconfig folder.

**Comment by JoelSzabo** [comment]
Thank you for your quick response! Worked like a treat :) Sad that I've lost the contents but at least I can open my world and use the mod again haha
