### ISSUE TITLE
How do I add it to my minecraft?

### ISSUE THREAD

**Issue by iiTokyoBxnny** [MC-U-Team/Usefull-Backpacks-1.10.x#71]
I have downloaded **uteamcore** and the useful **backpacks** **mod,** and I've added it to my **mods** folder but I don't see it in my game or anything like that and I don't know what to do.

**Comment by HyCraftHD** [comment]
Maybe you have not installed forge? If you don't know how to install mods the best way is to use the curseforge launcher and install usefulbackpacks with that
