### ISSUE TITLE
backpack filter configurator doesn't drop when broken

### ISSUE THREAD

**Issue by MoonMoonShark** [MC-U-Team/Usefull-Backpacks-1.10.x#77]
**Describe the bug**
when i break the Backpack Filter Configurator block, it disappears rather than dropping the item. The One Probe says it's expecting an axe, so i've used that, but also tried breaking by hand, with pickaxe, with shovel, and with sword. all result in the block disappearing rather than dropping.

**To Reproduce**
1. Place Backpack Filter Configurator in the world
2. Break Backpack Filter Configurator

**Expected behavior**
i expected to break the block, so i could put it in my inventory and move it, rather than obliterating it altogether.

**Screenshots**

**Versions**
- Mod version: useful_backpacks-1.16.5-1.12.0.89.jar
- Minecraft version: 1.16.5
- Forge version: 36.1.16
- UTeamCore version: u_team_core-1.16.5-3.2.1.195.jar

**Log (if crash occures)**
```
[27May2021 17:12:36.103] [Server thread/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report 1.16.5-3.0.1-forge ******************

 Found a Loot Table path that does not exist:  usefulbackpacks:blocks/filter_configurator
 The path represented by this Loot Table is:  data/usefulbackpacks/loot_tables/blocks/filter_configurator.json
 Loot Table method called at:  net.minecraft.block.AbstractBlock.func_220076_a
                               net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.
```

**Comment by HyCraftHD** [comment]
You are right, the loot table is missing. Will fix that. Thanks
