### ISSUE TITLE
[1.16.5] Game Crashed If The Mod Loaded with game

### ISSUE THREAD

**Issue by C-apy** [MC-U-Team/Usefull-Backpacks-1.10.x#83]
**Describe the bug**
The Mod Crashed my game if i load my single player world
**Screenshot Of the Errors**
![Screenshot_1](https://user-images.githubusercontent.com/57754485/127725979-8527492a-2d6f-4626-b453-51efa0bf7a24.png)

**Versions**
- Mod version: 1.16.5-1.12.1.90
- Minecraft version: 1.16.5
- Forge version: 36.1.62 (i think)
- UTeamCore version: 1.16.5-3.2.1.196

**Log (if crash occures)**
[2021-07-31-13.log](https://github.com/MC-U-Team/Useful-Backpacks/files/6910536/2021-07-31-13.log)

**Comment by HyCraftHD** [comment]
The log is not the one of the screenshot. Can you please upload the right log?

**Comment by C-apy** [comment]
my bad 
[crash-2021-07-31_10.10.35-server.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/6910948/crash-2021-07-31_10.10.35-server.txt)

**Comment by HyCraftHD** [comment]
Yea, your config file is corrupted. Please delete the usefulbackpacks-server.toml file in your world/serverconfigs directory

**Comment by C-apy** [comment]
What happends after that is the items in the backpacks is fully gone after the deletion of the toml files?

**Comment by HyCraftHD** [comment]
No, the backpack content is stored in the itemstack nbt data.
The configs are just some settings

**Comment by C-apy** [comment]
ah ok thanks
