### ISSUE TITLE
[1.16.5] My backpack deleted

### ISSUE THREAD

**Issue by HackYeah0** [MC-U-Team/Usefull-Backpacks-1.10.x#84]
I was mining while putting my stuff in my backpack, a creeper came out and exploded me. After i return to the place i died, backpack wasn't there. It just disappeared. Hopefully it will be solved soon with an update.

Steps to reproduce the behavior
1. Open backpack
2. Die while having it open

Expected behavior
I was expecting that backpack will drop with items in it so that i could regrab it like nothing happened.

- Mod version: 1.12.1.90
- Minecraft version: 1.16.5
- Forge version: 36.2.0
- UTeamCore version: 3.2.1.196

**Comment by HyCraftHD** [comment]
See #86 
Do you have any other mods installed`?

**Comment by HyCraftHD** [comment]
Closing because no response
