### ISSUE TITLE
[1.16.5] Backpack disappeared?

### ISSUE THREAD

**Issue by firestorm2039** [MC-U-Team/Usefull-Backpacks-1.10.x#86]
**Describe the bug**
i had recently made 2 backpacks (large and medium), the medium containing a load of wool and leather, i then saved my game, came back to it the next day and the medium backpack had gone?. this has happened previously as well on another world, i died and my backpack had gone with loads of diamonds, emeralds and other jewels in, i have another mod installed which saved all my items from disappearing when i die (even if i fall in lava or in the void), makes a gravestone, gives me a key and i can go get it all, so it wouldn't have been destroyed??

i have checked all my chests and my other backpack in case i put it in there, but its not there, its just vanished

**To Reproduce**
2. Do this '....'
it just dose it randomly i think, not seen a sequence as to how or why yet?

**Expected behavior**

**Screenshots**

**Versions**
- Mod version: useful_backpacks-1.16.5-1.12.1.90
- Minecraft version: ??? no idea, i assume 1.16.5??
- Forge version: 1.16.5 36.2.4
- UTeamCore version: u_team_core-1.16.5-3.2.1.196

**Log (if crash occures)**
Link to crash log

**Comment by javijmgdev** [comment]
the same thing just happened to me

**Comment by HyCraftHD** [comment]
Do you have any other mods installed that might control death items? 
The backpack might moved in some curious / baubles / custom inventory slots.

**Comment by firestorm2039** [comment]
i found my backpack. if you go on to craft (not crafting table) you will see an icon of yourself, in top left there is a icon, click that and it was in 1 of them slots, must have automatically went there when i collected items, no idea if that icon is from another mod or not??

**Comment by HyCraftHD** [comment]
Glad you found it!
Yes, must be an other mod then, as useful backpacks does change any gui stuff there.

**Comment by firestorm2039** [comment]
> Glad you found it! Yes, must be an other mod then, as useful backpacks does change any gui stuff there.

yeah, you click on that icon and a list of other slots come up (rings, back, head, legs etc), no idea what mod its from, i hadnt noticed it before, it was my 7 year old son that found it LOL

**Comment by hacheraw** [comment]
They are [Curios](https://www.curseforge.com/minecraft/mc-mods/curios) slots. Curios is an API used by Trinkets and other mods that add those extra slots.

And, actually, that's the best way to equip the backpack. When you press V it will open.
