### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EvenaXin** [MC-U-Team/Usefull-Backpacks-1.10.x#9]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: usefulbackpacks Failed load class: info.u_team.usefulbackpacks.UsefulBackpacksMod
[crash-2019-06-05_17.06.18-client.txt](https://github.com/MC-U-Team/Useful-Backpacks/files/3259475/crash-2019-06-05_17.06.18-client.txt)

**Comment by HyCraftHD** [comment]
Use a newer version of the mod.
This is the newest 1.12.2 release: https://minecraft.curseforge.com/projects/useful-backpacks/files/2719512
Please note, some crafting recipes have changed.

(You can also use an older uteamcore version (1.12.2-1.3.0.72)
